<?php
$GLOBALS['CONFIG']['PRODUCTION']['DB']['HOST'] = 'localhost';
$GLOBALS['CONFIG']['PRODUCTION']['DB']['USER'] = 'whitebride';
$GLOBALS['CONFIG']['PRODUCTION']['DB']['PASSWORD'] = 'wpGeiYZWt';
$GLOBALS['CONFIG']['PRODUCTION']['DB']['DBNAME'] = 'whitebride';
$GLOBALS['CONFIG']['PRODUCTION']['DB']['CHARSET'] = 'utf8';
$GLOBALS['CONFIG']['PRODUCTION']['DB']['COLLATE'] = 'utf8_general_ci';

 $GLOBALS['CONFIG']['PRODUCTION']['DB']['REDISDBID'] = 14;
?>